export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const GET_FOLLOWING_FEED = 'GET_FOLLOWING_FEED';
export const SET_PROFILE_LOADING = 'SET_PROFILE_LOADING';
export const SET_POSTS_LOADING = 'SET_POSTS_LOADING';
export const GET_POSTS = 'GET_POSTS';
export const GET_PROFILE_METRICS = 'GET_PROFILE_METRICS';
